version: '3.4'

services:

  stockcsv:
    image: stockcsv
    container_name: stock-csv-docker
    build:
      context: .
    ports:
      - 5000:80
      - 8000:443
    depends_on:
      - stockcsvdb

  stockcsvdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: stock-csv-db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password
    volumes:
      - sql-data:/var/lib/backup/data
volumes:
  sql-data: