version: '3.4'

services:

  stockcsv:
    container_name: stockcsv
    build:
      context: .
    ports:
      - 8080:80
      - 8081:443
    depends_on:
      - stockcsvdb

  stockcsvdb:
    image: mcr.microsoft.com/mssql/server:2022-RTM-CU2-ubuntu-20.04	
    container_name: stockcsvdb
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password